export const homeConstants = {
    FIX_HEADER: 'FIX_HEADER',
    TOGGLE_MENU: 'TOGGLE_MENU',
    FOCUS_LINK: 'FOCUS_LINK',
    START_FETCH_CARDS: 'START_FETCH_CARDS',
    FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_ERROR: 'FETCH_CARDS_ERROR',
};